
import { SovereignFingerprint } from '../types';
import { AuditReport, generateAuditMarkdown, computeIntegrityHash, AuditStatus } from './forensics';

/**
 * Generates a README/Manifest for the Proof Bundle to ensure the researcher
 * knows exactly what they are looking at and how to defend it.
 */
export function generateBundleManifest(data: SovereignFingerprint, report: AuditReport): string {
  return `
SOVEREIGN RELIABILITY PROOF BUNDLE (MANIFEST.txt)
================================================
ID: ${data.metadata.integrity_hash}
DATE: ${data.metadata.timestamp_utc}
BUILD: ${data.metadata.build}
VERDICT: ${AuditStatus[report.status]}

This bundle contains raw forensic evidence and audited conclusions 
for the SpiralOS Phase Controller reliability test.

MISSION CONFIGURATION:
----------------------
- Workers: ${data.config.workers}
- Base Offset: ${data.config.baseOffsetMs}ms
- Max Skew: ${data.config.maxSkewMs}ms
- Corridor: ${data.config.corridorMs}ms
- Gating (K): ${data.config.kStableTicks} ticks

OUTCOMES:
---------
- Max Sustainable Entropy (CSE): ${data.summary.maxSustainableEntropy}%
- Final Reliability Index (SPI): ${(data.summary.finalSPI * 100).toFixed(1)}%
- Total Samples: ${data.summary.samplesCount}
- Stability Resets: ${report.stabilityTrace.resets.length}
- Quality Breaches: ${report.stabilityTrace.degradedTicks.length}

INTEGRITY SIGNATURE:
--------------------
- Claimed Hash: ${data.metadata.integrity_hash}
- Recomputed:  ${computeIntegrityHash(data)}
- Verification: ${report.integrityHashMatch ? "PASSED" : "FAILED (TAMPERED)"}

Generated by SpiralOS Research Engine v1.1.
`;
}

/**
 * Generates a formal Repro Protocol document for peer review.
 */
export function generateReproProtocol(data: SovereignFingerprint): string {
  const hash = data.metadata.integrity_hash;
  return `
# Appendix A-2 — REPRO_PROTOCOL.md
## Artifact ID: ${hash}

This document outlines the steps required to independently verify and reproduce 
the results contained within this Proof Bundle.

### 1. Independent CLI Verification
Requires Node.js and the Sovereign Toolchain.
1. Place \`fingerprint-${hash}.json\` in a local directory.
2. Run integrity check:
   \`npm run audit:verify fingerprint-${hash}.json\`
3. Generate independent report:
   \`npm run audit:report fingerprint-${hash}.json --out audited-report.md\`
4. Compare \`audited-report.md\` against the bundled Appendix A-1.

### 2. High-Fidelity UI Replay
1. Launch the Sovereign Reliability Demonstrator.
2. Click "Import External" in the Audit Vault.
3. Select \`fingerprint-${hash}.json\`.
4. Observe the "Forensic Playback" mode.
5. Verify that the Diagnostic Matrix re-derives the SPI mean of ${(data.summary.finalSPI * 100).toFixed(1)}%.

### 3. Failure Conditions
Verification fails if:
- Integrity Hash Mismatch (Exit Code 2).
- Schema Corruption (Exit Code 3).
- Evidence Deficit (Exit Code 4): Stable ticks < ${data.config.kStableTicks}.

---
*Verified Protocol // SpiralOS Systems Group*
`;
}

/**
 * Formats the bundle for download using a sequenced multi-file strategy.
 */
export function downloadProofBundle(data: SovereignFingerprint, report: AuditReport) {
  const files = [
    { 
      name: `fingerprint-${data.metadata.integrity_hash}.json`, 
      content: JSON.stringify(data, null, 2), 
      type: 'application/json' 
    },
    { 
      name: `audit-report-${data.metadata.integrity_hash}.md`, 
      content: generateAuditMarkdown(data, report), 
      type: 'text/markdown' 
    },
    { 
      name: `MANIFEST-${data.metadata.integrity_hash}.txt`, 
      content: generateBundleManifest(data, report), 
      type: 'text/plain' 
    },
    { 
      name: `REPRO_PROTOCOL-${data.metadata.integrity_hash}.md`, 
      content: generateReproProtocol(data), 
      type: 'text/markdown' 
    }
  ];

  files.forEach((f, i) => {
    setTimeout(() => {
      const blob = new Blob([f.content], { type: f.type });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = f.name;
      link.click();
      URL.revokeObjectURL(url);
    }, i * 250); // Sequencing to bypass browser grouping
  });
}
